FlourishPlanner:
  environment_type: XYT_3dCollisions
  planner_type: ARAPlanner
  allocated_time: 10.0
  initial_epsilon: 5.0
  forward_search: true

  scene_update_name: /get_planning_scene
  allowed_collision_links:
    - wheel_fr_link
    - wheel_fl_link
    - wheel_rr_link
    - wheel_rl_link
